DROP TABLE IF EXISTS account_operations CASCADE;
DROP TABLE IF EXISTS credit CASCADE;
DROP TABLE IF EXISTS deposit CASCADE;
DROP TABLE IF EXISTS saving_account CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS currencys CASCADE;

DROP TYPE IF EXISTS operation_kind;
DROP TYPE IF EXISTS payment_method;
DROP TYPE IF EXISTS status;
DROP TYPE IF EXISTS account_type;
DROP TYPE IF EXISTS client_type;